# Unit tests of the functional-coverage runtime (odve_cov_pkg: the store,
# find_bin, find_trans, the dump). `source sourceme`, then
# `make ut` (ModelSim) or `make ut VERILATOR=1` - see script/common/ut.mk.
include ${ODVE}/script/common/ut.mk
