#PROJ=`pwd`

DEF=

RUN_OPTS += -batch

#FL_TB=$(ODVE)/comp/agents/apb/vrf/list/fl_tb.f
#FL_UVM=$(ODVE)/comp/agents/apb/vrf/list/fl_uvm.f
#FL_DUT=$(ODVE)/comp/agents/apb/vrf/list/fl_dut.f

COMP_OPTS+=

COV_OPTS+=

MAKE_RUN_OPTS+=

TESTNAME=

DUMP=

DUMP_TRAN=

COV=

UVM= 

COMP_CMD=

RUN_CMD=

COV_CMD=

include ${ODVE}/script/common/common.mk

